---
name: JSON Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # cancel any in-progress job or run
  # https://github.com/kdeldycke/workflows/commit/8bee3ba877
  # https://docs.github.com/actions/using-jobs/using-concurrency
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  json:
    name: Format JSON files and create a Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linter
        run: |
          command npm install @prantlf/jsonlint
      - name: Lint
        run: |
          command find -- . \
            -type f \
            ! -path '*/.git/*' \
            ! -path '*/node_modules/*' \
            ! -path '*vscode*' \
            '(' \
            -name '*.JSON' -o \
            -name '*.json' -o \
            -name '*.stats' -o \
            -name '*app-site-association' -o \
            -name '.dccache' -o \
            -name '.flutter' -o \
            -name '.flutter_tool_state' -o \
            -name '.imgbotconfig' -o \
            -name '.vs-liveshare-keychain' -o \
            -name '.vsconfig' -o \
            -name '.whitesource' \
            ')' \
            -exec npm exec -- @prantlf/jsonlint --in-place --prune-comments --trailing-newline --trim-trailing-commas -- '{}' ';'
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[autofix] format JSON content"
          title: "[autofix] format JSON content"
          body: >
            Auto-generated on [run #${{ github.run_id }}](${{
            github.event.repository.html_url }}/actions/runs/${{ github.run_id
            }}) as defined by [`jsonlint.yml` workflow](${{
            github.event.repository.html_url }}/blob/${{ github.sha
            }}/.github/workflows/jsonlint.yml).
          labels: enhancement, github_actions
          branch: format-json
          base: ${{ github.head_ref }}
